### ISSUE TITLE
callback only has init

### ISSUE THREAD

**Issue by teledyn** [ThomasAitken/Scrapy-Testmaster#1] opened 2020-05-11 19:19 UTC
This is likely due to the unusual structure of my crawler, but I find that it creates the directories with the `__init__.py` files, but the final directory for the call-back has only this file.  Is there a recommended strategy to finding out where it gets lost?

The structure of my crawler has three anomalies, first that it has two spiders, selected by the command line, and each of them is defined as subclasses of a common base, the second is that I don't generate db items, the output of my callback produces lists of dict items that my pipeline stashes in a graph database, and the third is a `-a` parameter that gives a specification filename that guides the crawl; the output from the testmaster shows that it selects all of these correctly. 

My settings.py contains
```
TESTMASTER_ENABLED = True
SPIDER_MIDDLEWARES = {
    'crawlbot.middlewares.MycrawlerSpiderMiddleware': 543,
    'scrapy_testmaster.TestMasterMiddleware': 950,
}
```
the spider middleware connects the spider_opened signal to log a stats value, process_spider_input returns None and process_spider_output iterates over the result.
Could the order of these be interfering?

I tried two command lines, one, based on my usual command line test of a single page:
```
testmaster parse "https://example.com/p/globe.html" --pipelines --callback find_pageset --spider crawler -a pageset=pagesets/crawler.pageset
```
the second form removes the --pipelines option but otherwise the same.

Let me know if there is any further information you would need.

**Comment by ThomasAitken** [comment] 2020-05-12 04:01
Thanks for being the first to create an issue!

If the spider gets properly loaded, then I don't really think the subclassing aspect should matter too much, although I might be wrong. Basically `testmaster parse` loads the spider exactly the same way as `scrapy parse`, so if it fails on that, then so does `scrapy parse` (or `testmaster parse` without middleware enabled). But I figure that this command doesn't fail on `scrapy parse`, right?

As for the item pipeline, basic item pipelines definitely work with the middleware. There could be something strange going on there, but without more info I can't say.

Meanwhile, my understanding of the spider middlewares is that the `process_spider_output` for TestMasterMiddleware should be executed first based on that order you've specified in settings.py ("and the process_spider_output() method of each middleware will be invoked in decreasing order" https://docs.scrapy.org/en/latest/topics/spider-middleware.html.) So that shouldn't affect anything either!

Given all that, my theory is that the `process_spider_output` function failed in TestMasterMiddleware. Is that correct? If it is, please attach the error log if there was one, because that will be really helpful. 

If there is an error log, does it look like this: "`AttributeError: Can't pickle local object 'Crawler.__init__.<locals>.<lambda>`'"? This is a bug with `testmaster parse` that I just discovered myself (!!!). It occurs in the function `add_sample` in `utils.py` when the callback result includes at least one request with a meta value that includes the key '_callback'. This would occur if your callback code contains something like the following:
```
metadata = response.meta [or response.meta.copy()]
...
#minor alterations
metadata["page"] += 1
...
yield Request(url_value, callback=self.cb_name, meta=metadata)
```
The key '_callback' in the response.meta is storing a bound method, so you could fix this by deleting this key from `metadata` or creating a new meta object for output requests... That being said, I'll quickly release a new version of the package in a few hours which makes sure you don't have to worry about this at all. So in a few hours you will be able to use that syntax without a problem.

If your error is not like that, I need more info.

**Comment by ThomasAitken** [comment] 2020-05-12 08:13
Ok, I changed one of the labels from "bug" to "question", because we're now at version 0.1.1 (`pip install --upgrade scrapy-testmaster`) and the issue I guessed you might be facing is resolved. If you are still facing your above issue after upgrading your version then clearly there is something else going on.

**Comment by ThomasAitken** [comment] 2020-05-13 02:06
Let me know if the issue is fixed or not. If not, I need more information.

**Comment by teledyn** [comment] 2020-05-13 18:03
Well, it didn't work, but maybe this might help?
```
2020-05-13 12:18:17 [scrapy.core.scraper] ERROR - Spider error processing <GET https://www.example.com/page.html> (referer: None)
Traceback (most recent call last):
  File "/home/garym/Work/TestCrawler/lib/python3.7/site-packages/twisted/internet/defer.py", line 654, in _runCallbacks
    current.result = callback(current.result, *args, **kw)
  File "/home/garym/Work/TestCrawler/lib/python3.7/site-packages/scrapy/core/spidermw.py", line 121, in process_callback_output
    return MutableChain(process_spider_output(result), recovered)
  File "/home/garym/Work/TestCrawler/lib/python3.7/site-packages/scrapy/core/spidermw.py", line 104, in process_spider_output
    result = method(response=response, result=result, spider=spider)
  File "/home/garym/Work/TestCrawler/lib/python3.7/site-packages/scrapy_testmaster/middleware.py", line 199, in process_spider_output
    add_sample(index, test_dir, test_name, data)
  File "/home/garym/Work/TestCrawler/lib/python3.7/site-packages/scrapy_testmaster/utils.py", line 111, in add_sample
    'data': pickle_data(data),
  File "/home/garym/Work/TestCrawler/lib/python3.7/site-packages/scrapy_testmaster/utils.py", line 134, in pickle_data
    return pickle.dumps(data, protocol=2)
AttributeError: Can't pickle local object 'LxmlLinkExtractor.__init__.<locals>.<lambda>'
2020-05-13 12:18:17 [scrapy.core.engine] INFO - Closing spider (finished)
```

I should add that I'm using Scrapy 2.1.0 on Ubuntu 19.10

**Comment by ThomasAitken** [comment] 2020-05-14 00:44
Ok so I think I've cracked this one. It's a general problem with CrawlSpiders, which I did not test on (my mistake!).

Try adding the following two lines to "process_spider_output" in "middlewares.py" after 
` spider_attr_out = {
            k: v for k, v in spider.__dict__.items()
            if k not in ('crawler', 'settings', 'start_urls')
        }
`
:
```
temp_rules = spider_attr_out.get('_rules', [])
spider_attr_out['_rules'] = [repr(rule) for rule in temp_rules]
```

Fingers crossed this works for you...

(Update: released another version which has this edit.)

There are still some other issues with using CrawlSpiders, which I'll try to work on soon..

**Comment by teledyn** [comment] 2020-05-14 20:02
I used the pip 0.1.2 but it looks to be the same error - I checked your middleware.py and see the above lines are in there, so your re-publish and my upgrade both worked, but the trace happens same place except add_sample is now line 201 -- oh and I notice that in my post above it looks like I posted the same trace twice; this is an artifact of my not having --nolog set -- I've corrected the above for clarity

**Comment by teledyn** [comment] 2020-05-14 20:11
This may be important: In my spider's self.rules, I instantiate 
```
        self.rules = (
            Rule(
                LinkExtractor(
                    allow=(''),
                    process_value=url_fix
                ),
                callback='find_pageset',
                follow=True),
        )
        super(SpiderCore, self).__init__(*a, **kw)
```
where url_fix is a variable set to a choice of local functions, not a class methods, one that drops any fragments from the URL, the other drops GET parameters as well.  Could that indirection cause the pickling to fail? (I am guessing in the dark)

**Comment by ThomasAitken** [comment] 2020-05-15 01:04
Perhaps... There's one last thing you can do for me if you would still like me to correct this, which is print out the state of data just before the following code in add_sample in utils.py:

```
 info = pickle_data({
        'data': pickle_data(data),
        'encoding': encoding,
        'fixture_version': FIXTURE_VERSION,
    })
```

Before these lines write: 
```
del data['response']
print(data)
```

Copy and paste what gets printed out minus any details you want to keep private.

**Comment by ThomasAitken** [comment] 2020-05-21 01:26
Seeing as you never applied to the above, I'm going to assume that you gave up. So I'm going to close this issue until someone else has a similar problem and can help me debug.

**Closed as completed by ThomasAitken** 2020-05-21 01:26 UTC
Labels: question

**Comment by teledyn** [comment] 2020-05-25 16:15
Sorry, I got distracted by other fires, hope to return to this later in the week
